use_frameworks!
platform :ios, '15.4'  # ios.deploymentTarget

target 'iosApp' do
  pod 'composeApp', :path => '../composeApp'
  pod 'GoogleMaps', '7.4.0' # latest version
end

# pod 'GoogleMaps', '7.4.0'
# pod 'Google-Maps-iOS-Utils', '4.2.2'